### ISSUE TITLE
attributeSortOrder Undefined

### ISSUE THREAD

**Issue by Selyam12** [ardittristan/VTTNPCGen#20]
I get an error on line 884 of NPCGenerator.js when generating an npc : attributeSortOrder of object is undefined, leading to error on foreach
![image](https://user-images.githubusercontent.com/61904162/111900826-f3e90800-8a34-11eb-83b6-44902e7a9251.png)

Does it mean the classesJSON is not correctly defined ?
Do I have to uninstall and reinstall to have the correct json ?

Thanks for your help.

**Comment by ardittristan** [comment]
you seem to have min/max stats enabled without adding it to the classesJSON (if you have added custom classes).
if you want'to use the min/max you should add the `attributeSortOrder` property to the classesJSON (updated the [examples](https://github.com/ardittristan/VTTNPCGen/blob/master/examples.md) since it got recently added).

or if you don't need it you can simply disable the min/max checkbox on the generator

**Comment by Selyam12** [comment]
Ok thanks
