### ISSUE TITLE
Ability to bulk generate a number of NPC's

### ISSUE THREAD

**Issue by mr-bo-jangles** [ardittristan/VTTNPCGen#5]
I have the need to generate ~200 NPC's and clicking over and over get's tiring

**Comment by ardittristan** [comment]
I'll probably add an api hook for this that you can use in a macro. Since making it very accessible for users to generate a big amount of actors in a small span of time seems very dangerous to the database file size to me. This way it'll still be possible, but a bit less accessible (and harder to accidentally misuse)

**Comment by mr-bo-jangles** [comment]
That'll work nicely, although you could make it send to a compendium if
you're worried about bloating the DB size?

**Comment by ardittristan** [comment]
I'll go for the api hook then! Though i don't have an eta since I'm currently working on porting external actor viewer to pf2e

**Comment by ardittristan** [comment]
added with 921a864
